# Generated by Django 5.2.4 on 2025-10-01 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Father', models.CharField(max_length=30)),
                ('Grand_Father', models.CharField(max_length=30)),
                ('ሙሉ_ስም', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Marital_Status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('Matric_Result', models.IntegerField()),
                ('Date_Of_Birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Place_Of_Birth', models.CharField(max_length=30)),
                ('Photo', models.ImageField(null=True, upload_to='photos/')),
                ('Nationality', models.CharField(max_length=20)),
                ('Region', models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Afar Region', 'Afar Region'), ('Amhara Region', 'Amhara Region'), ('Benishangul-Gumuz Region', 'Benishangul-Gumuz Region'), ('Central Ethiopia Region', 'Central Ethiopia Region'), ('Dire Dawa', 'Dire Dawa'), ('Gambela Region', 'Gambela Region'), ('Harari Region', 'Harari Region'), ('Oromia Region', 'Oromia Region'), ('Sidama Region', 'Sidama Region'), ('Somali Region', 'Somali Region'), ('South Ethiopia Region', 'South Ethiopia Region'), ("South West Ethiopia Peoples' Region", "South West Ethiopia Peoples' Region"), ('Tigray Region', 'Tigray Region')], max_length=50)),
                ('Disability', models.CharField(choices=[('None', 'No Disability'), ('Physical', 'Physical Disability'), ('Hearing', 'Hearing Impairment'), ('Visual', 'Visual Impairment'), ('Other', 'Other (Please specify)')], max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.IntegerField()),
                ('Registration_Number', models.IntegerField(null=True)),
                ('Tuition_Type', models.CharField(choices=[('cost_sharing', 'cost_sharing'), ('non-cafe', 'non-cafe')], max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('Street_Address', models.CharField(max_length=20, null=True)),
                ('Home_Tel_Phone', models.IntegerField(null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Work_Tel_Phone', models.IntegerField(null=True)),
                ('Woreda', models.CharField(null=True)),
                ('Kebele', models.CharField(null=True)),
                ('No', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=20)),
                ('Identity_Card', models.CharField(max_length=20, null=True)),
                ('Dormitary', models.CharField(max_length=10)),
                ('AdmissionYear', models.CharField(max_length=10, null=True)),
                ('Program', models.CharField(max_length=255, null=True)),
                ('Admission', models.CharField(max_length=255, null=True)),
                ('ClassYear', models.CharField(null=True, verbose_name=20)),
                ('Section', models.CharField(null=True, verbose_name=20)),
                ('No', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studentInformations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudent.student_informations')),
            ],
        ),
    ]
